### ISSUE TITLE
The Implementation of behavioral cloning and reinforcement learning agent training

### ISSUE THREAD

**Issue by JSA-458** [waymo-research/waymax#11]
Hello! I'm really impressed with this work.
I notice that waymax contains multi-agent trained with behavior cloning and reinforcement learning as baseline planning agents. Do you have any plan to open source the implementation of these agents in the future? Because I notice that the current agents support log-playback and IDM, I'm pretty looking forward to the implementation of behavior cloning and reinforcement learning agent training.
Thanks in advance for your reply！

**Comment by justinjfu** [comment]
Hi @JSA-458,

Unfortunately we can't release our training code as it depends on other code (such as the Wayformer architecture) which hasn't been released open-source yet. We'll try to get some reasonable benchmarks released in the future but I can't guarantee anything at the moment.
