### ISSUE TITLE
Alternative way of access the waymo library?

### ISSUE THREAD

**Issue by Gaochengzhi** [waymo-research/waymax#22]
I'm a Chinese user and I have struggled in install the Google CLI (all kinds of proxey issues)
 I have open access to the waymo datasets. Is there any other way to load the data?

**Comment by Gaochengzhi** [comment]
Instead of downloading dataset every time. Could it be store in somewhere on my disk?

**Comment by zzq-000** [comment]
Read source code of waymax, it’s not hard to change the code to read data from your disk.

**Comment by Gaochengzhi** [comment]
I tried to change path: str in config, should I first download waymo data into that file?

**Comment by zzq-000** [comment]
Of course, how could the program read data if no data in the local and you change the path from remote to local?
