### ISSUE TITLE
Questions about bicycle model with IDM

### ISSUE THREAD

**Issue by devzhouxx** [waymo-research/waymax#48]
I want to use a bicycle model to smooth the SDC trajectory, and other cars are controlled by IDM. But I found the following note:

`Note: The IDM policy is an actor hard-coded to use dynamics.StateDynamics().`

I tried to use a MultiAgentEnvironment with the bicycle model and found that the action space outputted by IDM is different.

I want to ask how to fix it more conveniently.

**Comment by tianyudwang** [comment]
@devzhouxx Did you figure out how to do this? I am also looking at the same problem.
