### ISSUE TITLE
Waymax visualization

### ISSUE THREAD

**Issue by hansungkim98122** [waymo-research/waymax#51]
Hi, I was wondering how we can visualize the simulation environment in the style shown in this reference picture:

![waymax_visualization](https://github.com/waymo-research/waymax/assets/89807906/15e792b4-f0af-4f01-b989-cb265abfddcc)

It seems like the Waymax package only offers more rudimentary visualization of the simulation environment shown below:
![waymax_visualization_rudi](https://github.com/waymo-research/waymax/assets/89807906/e1c1d3d3-e520-44f1-ad44-aa3236656447)

Any help or guidance is appreciated! Thanks.

**Comment by Jin0932** [comment]
@hansungkim98122 Hi, have you solve it?

**Comment by RomanChiva** [comment]
I have the same issue, any updates?

**Comment by hansungkim98122** [comment]
Unfortunately, no. Not sure if it is possible
