### ISSUE TITLE
Out of memory when use the "next(self.scenario_generator)"

### ISSUE THREAD

**Issue by Ansansniper1** [waymo-research/waymax#66]
Hi, Very Nice Work!!

I'm currently working on creating a simple architecture using imitation learning. However, I found an issue using the following code to create my dataset. Specifically, when I use "data = next(self.scenario_generator)", I notice that GPU memory usage increases rapidly (1G --> 20G+). I’m not sure how to resolve this problem.

I would appreciate any help, Thanks!

Here is my dataprocess code, I tried to use some methods like this "torch.from_numpy(jax.device_get(log_trajectory.yaw))" to deal with the scenario data.

```python
def custom_collate_fn(batch):
    ...
    return batch_data

class ScenarioDataset(torch.utils.data.Dataset):
    def __init__(self, scenario_generator):
        self.scenario_generator = scenario_generator
        self.num_samples = 487001
        
    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        data = next(self.scenario_generator)
        return data

**Comment by samuela** [comment]
TensorFlow will by default allocate ~all of your GPU memory. See eg https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory for more info.
